apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networkdevices.netops.example.com
spec:
  group: netops.example.com
  scope: Namespaced
  names:
    plural: networkdevices
    singular: networkdevice
    kind: NetworkDevice
    shortNames:
      - nd
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["endpoint", "platform"]
              properties:
                endpoint:
                  type: object
                  required: ["address"]
                  properties:
                    address:
                      type: string
                      description: "Management address (IP or DNS)."
                    port:
                      type: integer
                      minimum: 1
                      maximum: 65535
                      default: 443
                      description: "Management port."
                platform:
                  type: object
                  required: ["vendor", "os"]
                  properties:
                    vendor:
                      type: string
                      description: "Vendor name (e.g., cisco, juniper, arista)."
                    os:
                      type: string
                      description: "Network OS (e.g., nxos, eos, junos, sonic)."
                    model:
                      type: string
                      description: "Optional hardware model."
                role:
                  type: string
                  description: "Optional role (spine/leaf/etc)."
                transport:
                  type: string
                  description: "Preferred transport/protocol."
                  enum: ["gnmi", "netconf", "rest", "cli"]
                credentialsRef:
                  type: object
                  required: ["name"]
                  properties:
                    name:
                      type: string
                      description: "Secret name containing credentials."
                    namespace:
                      type: string
                      description: "Optional secret namespace (default: same namespace)."
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum: ["unknown", "reachable", "unreachable", "error"]
                lastSeen:
                  type: string
                  format: date-time
                message:
                  type: string
                capabilities:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true

